Drivers:
  RopePin:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F09
    direction: 'input'
    mode: 'digital'

  StarterDriver:
    type: 'rope' # keyboard, rope
    "@dependencies":
      ropePin: RopePin

  MotionDriver:
    startPosition: [ -610, -790, [ -610, -790, 'yellow' ], [ 610, -790, 'blue' ] ]
    startOrientation: [ -90, [ -90, 'yellow' ] ]
    startSpeed: 100
    refreshDataPeriod: 120

  CanDriver:
    "@class": drivers/can/CanDriver

  Lidar:
    "@class": drivers/lidar/LidarDriver
    "@load": true
    cid: 0x00000100
    minDistance: 200
    "@dependencies":
      communicator: CanDriver

  LaserBackLeft:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: 70
    cid: 0x00007F0C
    objectSize: 150

  LaserBackRight:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: -70
    cid: 0x00007F0F
    objectSize: 150

  LaserFrontCenter:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 300
    sensorAngle: 90
    sensorX: 0
    sensorY: 70
    cid: 0x00007F0B
    objectSize: 150

  LaserFrontLeft:
    "@class": drivers/infrared/InfraredDriver
    "@load": false
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 300
    sensorAngle: 110
    sensorX: 0
    sensorY: 70
    cid: 0x00007F11
    objectSize: 150

  LaserFrontRight:
    "@class": drivers/infrared/InfraredDriver
    "@load": false
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 300
    sensorAngle: 60
    sensorX: 0
    sensorY: 70
    cid: 0x00007F23
    objectSize: 150

  ColorSensor:
    "@class": drivers/color/ColorDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x000005D1
    tolerance: 10
    type: 'hsv'
    colors:
      # yellow: [ 0xfe, 0xf7, 0xdc ]
      # blue: [ 0xb4, 0xdb, 0xf1 ]
      yellow: [ 28, 32, 250 ]
      blue: [ 155, 32, 230 ]

  ServoCollectorStopper:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 6
    cid: 0x00007F00

  VacuumPump:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F02
      direction: 'output'
      mode: 'digital'

  Cylinder:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F03
      direction: 'output'
      mode: 'digital'

  FunnyServo:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x000005D2
    direction: 'output'
    mode: 'analog'
    max: 30

  ServoCollectorTrackLeft:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 1
    cid: 0x00007F01

  ServoCollectorHandLeft:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 2
    cid: 0x00007F00

  ServoPump:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 5
    cid: 0x00007F00

  ServoCollectorTrackRight:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 2
    cid: 0x00007F01

  ServoLimiter:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 6
    cid: 0x00007F00

  ServoCollectorHandRight:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 11
    cid: 0x00007F00

  CollectorBigTrack:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F06
    direction: 'output'
    mode: 'digital'

  BackLunarDetector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F10
    direction: 'input'
    mode: 'digital'

  FrontLunarDetector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F0E
    direction: 'input'
    mode: 'digital'

  MiddleLunarDetector:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F0D
      direction: 'input'
      mode: 'digital'

  ColorRotator:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F12
    min: 0
    max: 255
    direction: 'output'
    mode: 'analog'

  ColorRotator2:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F07
    direction: 'output'
    mode: 'digital'

  CircularEjector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F05
    direction: 'output'
    mode: 'digital'

  CircularInjector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F08
    direction: 'output'
    mode: 'digital'

  ColorServo:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 7
    cid: 0x00007F00

  LunarCollector:
    "@class": drivers/lunarcollector/LunarCollectorDriver
    "@load": true
    "@dependencies":
      leftTrack: ServoCollectorTrackLeft
      rightTrack: ServoCollectorTrackRight
      leftHand: ServoCollectorHandLeft
      rightHand: ServoCollectorHandRight
      bigTrack: CollectorBigTrack
      limiter: ServoLimiter
      servoPump: ServoPump
      vacuumPump: VacuumPump
      cylinder: Cylinder
      circularEjector: CircularEjector
      frontDetector: FrontLunarDetector
      backDetector: BackLunarDetector
      middleDetector: MiddleLunarDetector
      colorRotator: ColorRotator
      colorRotator2: ColorRotator2
      colorSensor: ColorSensor
      colorServo: ColorServo
      circularInjector: CircularInjector

Services:
  MotionService:
    moveOptions:
      obstacle: 5000
