Drivers:
  RopePin:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F09
    direction: 'input'
    mode: 'digital'

  StarterDriver:
    type: 'rope'
    "@dependencies":
      ropePin: RopePin

  MotionDriver:
    startPosition: [ -610, -790, [ -610, -790, 'yellow' ], [ 610, -790, 'blue' ] ]
    startX: -610
    startY: -790
    startOrientation: [ -90, [ -90, 'yellow' ] ]
    startSpeed: 100
    refreshDataPeriod: 100

  CanDriver:
    "@class": drivers/can/CanDriver

  Lidar:
    "@class": drivers/lidar/LidarDriver
    "@load": true
    cid: 0x00000100
    "@dependencies":
      communicator: CanDriver

  LaserBackLeft:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: 70
    cid: 0x00007F0C
    objectSize: 150

  LaserBackRight:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: -70
    cid: 0x00007F0B
    objectSize: 150

  LaserFrontCenter:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: 90
    sensorX: 0
    sensorY: 70
    cid: 0x00007F0F
    objectSize: 150

  ColorCollector:
    "@class": drivers/color/ColorDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 1501
    colors:
      yellow: [ 210, 185, 155 ]
      blue: [ 140, 140, 170 ]
      white: [ 210, 210, 210 ]

  ServoCollectorStopper:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 6
    cid: 0x00007F00

  VacuumPump:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F02
      direction: 'output'
      mode: 'digital'

  Cylinder:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F03
      direction: 'output'
      mode: 'digital'

  ServoCollectorTrackLeft:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 4
    cid: 0x00007F00

  ServoCollectorHandLeft:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 2
    cid: 0x00007F00

  ServoPump:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 5
    cid: 0x00007F00

  ServoCollectorTrackRight:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 9
    cid: 0x00007F00

  ServoLimiter:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 6
    cid: 0x00007F00

  ServoCollectorHandRight:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 11
    cid: 0x00007F00

  CollectorBigTrack:
    "@class": drivers/hbridge/HBridgeDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F13

  CircularEjector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F04
    direction: 'output'
    mode: 'digital'

  BackLunarDetector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F10
    direction: 'input'
    mode: 'digital'

  FrontLunarDetector:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F0E
    direction: 'input'
    mode: 'digital'

  MiddleLunarDetector:
      "@class": drivers/pin/PinDriver
      "@load": true
      "@dependencies":
        communicator: CanDriver
      cid: 0x00007F0D
      direction: 'input'
      mode: 'digital'

  LunarCollector:
    "@class": drivers/lunarcollector/LunarCollectorDriver
    "@load": true
    "@dependencies":
      leftTrack: ServoCollectorTrackLeft
      rightTrack: ServoCollectorTrackRight
      leftHand: ServoCollectorHandLeft
      rightHand: ServoCollectorHandRight
      bigTrack: CollectorBigTrack
      limiter: ServoLimiter
      servoPump: ServoPump
      vacuumPump: VacuumPump
      cylinder: Cylinder
      circularEjector: CircularEjector
      frontDetector: FrontLunarDetector
      backDetector: BackLunarDetector
      middleDetector: MiddleLunarDetector