Drivers:
  StarterDriver:
    type: 'keyboard'

  MotionDriver:
    "@class": "drivers/motion/MotionDriverSimulator"
    "@dependencies":

  CanDriver:
    "@class": "drivers/can/CanDriverSimulator"

  Uart:
    "@load": 0xff