simulation: true
table: ''
performance: false
robot: ''
scheduler: ''
host: ''
obstacleMaxPeriod: 300
Log:
  Console:
    active: true
    outputMode: short
    color: true
  File:
    active: false
    file: javascript.log
    period: 1d
    count: 3
Telemetry:
  port: 1200
Drivers:
  Uart:
    "@class": drivers/uart/Uart
    "@load": true
    protocol: PLLSP

  MotionDriver:
    "@class": drivers/motion/MotionDriver
    "@load": true
    "@dependencies":
      communicator: Uart
    startSpeed: 100
    precision: 2
    refreshDataPeriod: 120

  MotionDriverController:
    "@class": drivers/motion/MotionDriverController
    "@load": true
    "@dependencies":
      motionDriver: MotionDriver

  CanDriver:
    "@class": drivers/can/CanDriver
    "@load": true
    device: can0
    bitrate: 500000

  StarterDriver:
    "@class": drivers/starter/StarterDriver
    "@load": true
    type: keyboard
    delayTimer: 400
  UsageDriver:
    "@class": drivers/usage/UsageDriver
    "@load": true
    refreshPeriod: 600
Services:
  PositionService:
  MotionService:
    hazardObstacleDistance: 450
    moveOptions:
      rerouting: false
      pf: false
      backward: false
      relative: false
      tolerance: -1
      speed: 100
      radius: 80
    rotateOptions:
      relative: false
  TerrainService:
    staticObstacles:
    - - x: -550
        y: 1001
      - x: -700
        y: 370
      - x: 0
        y: 20
      - x: 700
        y: 370
      - x: 550
        y: 1001
    - - x: -790
        y: 1001
      - x: -950
        y: 400
      - x: -1501
        y: 330
    - - x: -1501
        y: -550
      - x: -850
        y: -200
      - x: -600
        y: -400
      - x: -600
        y: -1001
  SchedulerService:
  ShareService:
