simulation: true
table: ''
performance: false
robot: ''
scheduler: ''
host: ''
obstacleMaxPeriod: 300
duration: 90
volume: 1280
friendIp: 192.168.12.145

Log:
  Console:
    active: true
    outputMode: short
    color: true
  File:
    active: false
    file: javascript.log
    period: 1d
    count: 3
Telemetry:
  port: 1200
Drivers:
  MotionDriver:
    "@class": drivers/motion/MotionDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 600
    startSpeed: 100
    precision: 2
    refreshDataPeriod: 100

  CanDriver:
    "@class": drivers/can/CanDriver
    "@load": true
    device: can0
    bitrate: 500000

  StarterDriver:
    "@class": drivers/starter/StarterDriver
    "@load": true
    type: keyboard
    delayTimer:

Services:
  PositionService:
  MotionService:
    hazardObstacleDistance: 450
    moveOptions:
      obstacle: 90000
      friend: 90000
      rerouting: false
      pf: false
      backward: false
      relative: false
      tolerance: -1
      speed: 100
      radius: 80
    rotateOptions:
      relative: false
  TerrainService:
    staticObstacles:
    # Middle
    - [{ x: -550, y: 1001 }, { x: -700, y: 370 }, { x: 0, y: 20 }, { x: 700, y: 370 }, { x: 550, y: 1001 }]

    # Our corner
    - [{ x: -790, y: 1001 }, { x: -950, y: 400 }, { x: -1501, y: 330 }]

    # Our start position
    - [{ x: -1501, y: -550 }, { x: -1100, y: -500 }, { x: -850, y: -100 }, { x: -600, y: -400 }, { x: -600, y: -1001 }]


    # Their start position
    - [{ x: 1501, y: -550 }, { x: 1100, y: -500 }, { x: 850, y: -100 }, { x: 600, y: -400 }, { x: 600, y: -1001 }]

    # Their corner
    - [{ x: 790, y: 1001 }, { x: 950, y: 400 }, { x: 1501, y: 330 }]

    # Our side cartridge
    - [{ x: -1500, y: 220 }, { x: -1300, y: 220 }, { x: -1300, y: -350 }, { x: -1500, y: -350 } ]

    # Their side cartridge
    - [{ x: 1500, y: 220 }, { x: 1300, y: 220 }, { x: 1300, y: -350 }, { x: 1500, y: -350 } ]

  SchedulerService:
  ShareService:
