Drivers:
  StarterDriver:
    type: 'keyboard'

  MotionDriver:
    startPosition: [ -1350, -790, [ 1350, -790, 'blue' ] ]
    startOrientation: [ 90, [ 90, 'yellow' ] ]
    startSpeed: 100
    refreshDataPeriod: 120

  Servo:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 1
    cid: 0x00007F00

  ColorRotator1:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F13
    min: 0
    max: 255
    direction: 'output'
    mode: 'analog'

  ColorRotator2:
    "@class": drivers/pin/PinDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    cid: 0x00007F14
    min: 0
    max: 255
    direction: 'output'
    mode: 'analog'

  DirectionBall:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 20
    cid: 0x00007F00

  ColorRamp:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 21
    cid: 0x00007F00

  BallPicker:
    "@class": drivers/dynamixel/DynamixelDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    id: 50
    cid: 0x00007F00

  LaserBack:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: -70
    cid: 0x00007F21
    objectSize: 150

  LaserFront:
    "@class": drivers/infrared/InfraredDriver
    "@load": true
    "@dependencies":
      communicator: CanDriver
    infraredMaxDistance: 200
    sensorAngle: -90
    sensorX: 100
    sensorY: -70
    cid: 0x00007F11
    objectSize: 150

Services:
  MotionService:
    moveOptions:
      obstacle: 1500
      friend: 1000