table: ''
simulation: true
performance: true
Log:
  Console:
    active: true
    outputMode: short
    color: true
Telemetry:

Drivers: 
 MotionDriver: 
  "@class": "drivers/motion/MotionDriverSimulator"
  "@load": true
  startPosition: [ -610, -790, [ -610, -790, 'yellow' ], [ 610, -790, 'blue' ] ]
  startOrientation: [ -90, [ -90, 'yellow' ] ]

 CanDriver: 
  "@class": "drivers/can/CanDriverSimulator"
  "@load": true

 StarterDriver: 
  "@class": "drivers/starter/StarterDriver"
  "@load": true
  type: keyboard
  delayTimer: 400

Services:
 TerrainService:
  staticObstacles: []

 PositionService:

  MotionService:
    hazardObstacleDistance: 450
    moveOptions:
      obstacle: 90000
      friend: 90000
      rerouting: false
      pf: false
      backward: false
      relative: false
      tolerance: -1
      speed: 100
      radius: 80
    rotateOptions:
      relative: false